collections:
    h:
        index_paths: $liveweb
        frame_insert_html: ./templates/frame_insert.html
        head_insert_html: ./templates/head_insert.html
        search_html: ./templates/index.html
        redir_to_exact: false
        cookie_scope: exact

home_html: ./templates/index.html

static_routes:
    static/default: pywb/static/
    static/ann: ./static/

framed_replay: false
