collections:
    live:
        index_paths: $liveweb
        frame_insert_html: ./templates/frame_insert.html
#        banner_html: ./templates/banner.html
        head_insert_html: ./templates/head_insert.html
        redir_to_exact: false

enable_cdx_api: true

static_routes:
    static/default: pywb/static/
    static/ann: ./static/
    assets: ./static/assets/

framed_replay: true
