pdf_viewer: &pdf_viewer 'pdfjs_viewer.html'

collections:
    '':
        index_paths: $liveweb
        wb_handler_class: !!python/name:pywb_h.TemplateRewriteHandler
        templates:
            'application/pdf': *pdf_viewer
            'application/x-pdf': *pdf_viewer

        #frame_insert_html: ./templates/frame_insert.html
        #head_insert_html: ./templates/head_insert.html
        redir_to_exact: false

        #cookie_scope: host

        rewrite_opts:
            rewrite_rel_canon: false
            client:
                no_rewrite_prefixes:
                    - 'https://hypothes.is/'
                    - '/assets/'

                #skip_createElement: true

                http_cache: pass

                #skip_setAttribute: true
                #skip_dom: true
                #skip_postmessage: true

    # redirect old path to root
    h: !!python/object:pywb_h.SimpleRedirHandler { redir_path: '/', status: '301 Permanent Redirect' }

search_html: index.html
home_html: index.html

static_routes:
    static/__pywb: pywb/static/
    static/pdfjs: static/viewer/

framed_replay: false
