pdf_redir: &pdf_redir '/static/__shared/viewer/web/viewer.html?file={0}'

collections:
    '':
        index_paths: $liveweb
        wb_handler_class: !!python/name:pywb_h.CustomRedirHandler
        redirects:
            'application/pdf': *pdf_redir
            'application/x-pdf': *pdf_redir

        #frame_insert_html: ./templates/frame_insert.html
        #head_insert_html: ./templates/head_insert.html
        redir_to_exact: false

        #cookie_scope: host

        rewrite_opts:
            rewrite_rel_canon: false
            rewrite_base: false
            client:
                no_rewrite_prefixes:
                    - 'https://hypothes.is/'
                    - '/assets/'

                #skip_createElement: true

                http_cache: pass

                #skip_setAttribute: true
                #skip_dom: true
                #skip_postmessage: true

    # redirect old path to root
    h: !!python/object:pywb_h.SimpleRedirHandler { redir_path: '/', status: '301 Permanent Redirect' }
    
search_html: index.html
home_html: index.html

static_routes:
    static/__pywb: pywb/static/
    static/ann: ./static/

framed_replay: false
